###############################################
# ┌─────────────────────────────────────────┐ #
# │                  ZCore                  │ #
# └─────────────────────────────────────────┘ #
###############################################

# ┌───────────────────────────┐
# │          General          │
# └───────────────────────────┘

# In what interval should data be automatically saved
autoSaveTime: 300

# If all players should be precached when ZCore loads
precacheAllPlayers: false

# The path to the folder where backups should be stored.
# This can be a relative or absolute file path.
backupFolder: './backup'

# Message of the day
# Set to '' to disable
motd:
  - '§eWelcome, {NAME}§e!'
  - '§bType /help for a list of commands.'
  - '§7Online players: §f{PLAYERLIST}'

rules:
  - '§c1. Be respectful'
  - '§c2. No griefing'
  - '§c3. No cheating'

# After how long will inactive players be marked as AFK
afkTime: 300

# After how long will AFK players be kicked
afkKickTime: 1800

afkKickReason: '§cYou have been kicked for inactivity'

# Makes AFK players invincible and freezes them in place
# Players have to type /afk to unfreeze themselves
protectAfkPlayers: false

# If protectAfkPlayers is enabled, how long do players
# have to stand still until they are marked as AFK
afkDelay: 3

# ┌───────────────────────────┐
# │           Chat            │
# └───────────────────────────┘

chatFormat: '{DISPLAYNAME}§f: {MESSAGE}'
broadcastFormat: '§d[Broadcast] {MESSAGE}'
joinMsgFormat: '§e{PLAYER} has joined the game'
leaveMsgFormat: '§e{PLAYER} has left the game'
kickMsgFormat: '§e{PLAYER} has been kicked from the server'
banMsgFormat: '§e{PLAYER} has been banned from the server'

# The prefix to add to nicknames to differentiate them from real names
nickPrefix: '~'

nickFormat: '{PREFIX} §f{NICKNAME}§f {SUFFIX}'

# How far away a player will be heard from when chatting
# Set to 0 to make chat global
chatRadius: 0

msgSendFormat: '§7[me -> {NAME}§7] §f{MESSAGE}'
msgReceiveFormat: '§7[{NAME}§7 -> me] §f{MESSAGE}'

# ┌───────────────────────────┐
# │          Economy          │
# └───────────────────────────┘

# The currency to prefix balances with
currency: '$'

# The highest balance a player can have
# This value is hard-capped to 10,000,000,000,000
maxBalance: 10000000000000

# How many balances should be shown on a page in /balancetop
balancesPerPage: 10

# ┌───────────────────────────┐
# │           Homes           │
# └───────────────────────────┘

# How many homes are players with zcore.sethome.multiple allowed to have
multipleHomes: 10

# How many homes should be shown on a page in /homes
homesPerPage: 50

# ┌───────────────────────────┐
# │        Punishments        │
# └───────────────────────────┘

# Kicks
defaultKickReason: 'Kicked from server'
kickFormat: '§cYou have been kicked: {REASON}'

# Bans
defaultBanReason: 'The ban hammer has spoken!'
permBanFormat: '§cYou have been permanently banned: {REASON}'
tempBanFormat: '§cYou have been banned until {DATETIME}: {REASON}'
permIpBanFormat: '§cYour IP has been permanently banned: {REASON}'
tempIpBanFormat: '§cYour IP has been banned until {DATETIME}: {REASON}'