###############################################
# ┌─────────────────────────────────────────┐ #
# │                  ZCore                  │ #
# └─────────────────────────────────────────┘ #
###############################################

# ┌───────────────────────────┐
# │          General          │
# └───────────────────────────┘

# In what interval should data be automatically saved
autoSaveTime: 300

broadcastFormat: '&d[Broadcast] {MESSAGE}'

# Message of the day
# Set to '' to disable
motd:
  - '&eWelcome, {USERNAME}&e!'
  - '&bType /help for a list of commands.'
  - '&7Online players: &f{LIST}'

rules:
  - '&c1. Be respectful'
  - '&c2. No griefing'
  - '&c3. No cheating'

# ┌───────────────────────────┐
# │          Economy          │
# └───────────────────────────┘

# The highest balance a player can have
# This value is hard-capped to 10,000,000,000,000
maxBalance: 10000000000000

# ┌───────────────────────────┐
# │           Homes           │
# └───────────────────────────┘

# How many homes are players with zcore.sethome.multiple allowed to have
multipleHomes: 10

# How many homes should be shown on a page in /homes
homesPerPage: 50

# ┌───────────────────────────┐
# │        Punishments        │
# └───────────────────────────┘

# Kicks
defaultKickReason: 'Kicked from server'
kickFormat: '&cYou have been kicked: {REASON}'

# Bans
defaultBanReason: 'The ban hammer has spoken!'
permBanFormat: '&cYou have been permanently banned: {REASON}'
tempBanFormat: '&cYou have been banned until {DATETIME}: {REASON}'
permIpBanFormat: '&cYour IP has been permanently banned: {REASON}'
tempIpBanFormat: '&cYour IP has been banned until {DATETIME}: {REASON}'